sdzblog_accueil:
    pattern:   /blog
    defaults:  { _controller: SdzBlogBundle:Blog:index }
    
sdzblog_voir_article:
    pattern:   /blog/{id}
    defaults:  { _controller: SdzBlogBundle:Blog:voir }
    
sdzblog_liste_articles:
    pattern:   /blog/liste/{page}
    defaults:  { _controller: SdzBlogBundle:Blog:liste, page: 1 }
    requirements:
        page:  \d+